#!/usr/bin/env python3
"""
Keyword Matrix — 100 SEO Blog Topics for Xe Cẩu Giang Khôi
Organized by priority tier: urgent/high-margin first, then SEO balance.
"""

import json
import os

KEYWORDS = [
    # ═══════════════════════════════════════════════════════════════
    # TIER 1: URGENT — Nhu cầu gấp, lợi nhuận cao nhất (30 bài)
    # ═══════════════════════════════════════════════════════════════

    # --- Cứu hộ khẩn cấp theo khu vực ---
    {"id": 1, "slug": "cuu-ho-xe-tai-lat-hung-yen", "title": "Cứu Hộ Xe Tải Lật Hưng Yên — Có Mặt 30 Phút, 24/7", "description": "Dịch vụ cứu hộ xe tải lật tại Hưng Yên. Đội cẩu 6 xe có mặt trong 30 phút. Xử lý an toàn, nhanh chóng. Gọi 0971 491 174.", "category": "cuu-ho", "priority": "tier1", "area": ["Hưng Yên"], "tags": ["cứu hộ", "xe tải lật", "Hưng Yên", "24/7"], "keywords": {"primary": "cứu hộ xe tải lật Hưng Yên", "secondary": ["xe cứu hộ Hưng Yên", "cẩu xe lật Hưng Yên"], "lsi": ["xe tải bị lật", "kéo xe tải", "cẩu cứu hộ gấp"]}},
    {"id": 2, "slug": "cuu-ho-xe-tai-lat-ha-noi", "title": "Cứu Hộ Xe Tải Lật Hà Nội — Xe Cẩu Gấp 24/7", "description": "Cẩu cứu hộ xe tải lật tại Hà Nội. Có mặt nhanh, xử lý chuyên nghiệp. Đội 6 xe 3.5T–100T sẵn sàng. Hotline: 0971 491 174.", "category": "cuu-ho", "priority": "tier1", "area": ["Hà Nội"], "tags": ["cứu hộ", "xe tải lật", "Hà Nội"], "keywords": {"primary": "cứu hộ xe tải lật Hà Nội", "secondary": ["cẩu xe lật Hà Nội", "xe cứu hộ Hà Nội"], "lsi": ["tai nạn xe tải", "lật xe quốc lộ"]}},
    {"id": 3, "slug": "cuu-ho-xe-tai-lat-bac-ninh", "title": "Cứu Hộ Xe Tải Lật Bắc Ninh — Xe Cẩu Có Mặt Nhanh", "description": "Dịch vụ cứu hộ xe tải lật Bắc Ninh. Cẩu chuyên nghiệp, có mặt nhanh chóng. Phục vụ KCN Quế Võ, Tiên Du, Yên Phong. Gọi ngay!", "category": "cuu-ho", "priority": "tier1", "area": ["Bắc Ninh"], "tags": ["cứu hộ", "xe tải lật", "Bắc Ninh"], "keywords": {"primary": "cứu hộ xe tải lật Bắc Ninh", "secondary": ["cẩu xe lật Bắc Ninh", "xe cứu hộ KCN Bắc Ninh"], "lsi": ["KCN Quế Võ", "đường cao tốc"]}},
    {"id": 4, "slug": "cuu-ho-xe-tai-lat-bac-giang", "title": "Cứu Hộ Xe Tải Lật Bắc Giang — Cẩu Gấp 24/7", "description": "Xe cẩu cứu hộ xe tải lật tại Bắc Giang. Phục vụ KCN Việt Yên, Yên Dũng. Có mặt nhanh, an toàn. Gọi 0971 491 174.", "category": "cuu-ho", "priority": "tier1", "area": ["Bắc Giang"], "tags": ["cứu hộ", "xe tải lật", "Bắc Giang"], "keywords": {"primary": "cứu hộ xe tải lật Bắc Giang", "secondary": ["cẩu xe lật Bắc Giang"], "lsi": ["KCN Việt Yên", "quốc lộ 1A"]}},
    {"id": 5, "slug": "cuu-ho-xe-tai-lat-thai-binh", "title": "Cứu Hộ Xe Tải Lật Thái Bình — Xe Cẩu 24/7", "description": "Dịch vụ cứu hộ xe tải lật Thái Bình. Đội cẩu chuyên nghiệp, có mặt nhanh. Phục vụ mọi tuyến đường Thái Bình. Hotline 24/7.", "category": "cuu-ho", "priority": "tier1", "area": ["Thái Bình"], "tags": ["cứu hộ", "xe tải lật", "Thái Bình"], "keywords": {"primary": "cứu hộ xe tải lật Thái Bình", "secondary": ["cẩu xe lật Thái Bình"], "lsi": ["KCN Tiền Hải", "quốc lộ 10"]}},

    # --- Xe cẩu gấp theo khu vực ---
    {"id": 6, "slug": "xe-cau-gap-hung-yen-24-7", "title": "Xe Cẩu Gấp Hưng Yên 24/7 — Có Mặt Trong 30 Phút", "description": "Cần xe cẩu gấp tại Hưng Yên? Giang Khôi có mặt trong 30 phút. Đội 6 xe 3.5T–100T, phục vụ 24/7. Gọi ngay 0971 491 174.", "category": "cuu-ho", "priority": "tier1", "area": ["Hưng Yên"], "tags": ["xe cẩu gấp", "Hưng Yên", "24/7"], "keywords": {"primary": "xe cẩu gấp Hưng Yên", "secondary": ["thuê xe cẩu gấp Hưng Yên", "cẩu gấp 24/7 Hưng Yên"], "lsi": ["cẩu khẩn cấp", "có mặt nhanh"]}},
    {"id": 7, "slug": "xe-cau-gap-ha-noi", "title": "Xe Cẩu Gấp Hà Nội — Điều Phối Nhanh Từ Hưng Yên", "description": "Thuê xe cẩu gấp tại Hà Nội. Điều xe từ Mỹ Hào, Hưng Yên. Cẩu 3.5T–100T sẵn sàng. Phục vụ Gia Lâm, Long Biên, Hoàng Mai.", "category": "cuu-ho", "priority": "tier1", "area": ["Hà Nội"], "tags": ["xe cẩu gấp", "Hà Nội"], "keywords": {"primary": "xe cẩu gấp Hà Nội", "secondary": ["thuê cẩu gấp Hà Nội"], "lsi": ["Gia Lâm", "Long Biên"]}},
    {"id": 8, "slug": "xe-cau-gap-bac-ninh", "title": "Xe Cẩu Gấp Bắc Ninh — Cẩu Nhanh, Giá Tốt", "description": "Dịch vụ xe cẩu gấp Bắc Ninh. Có mặt nhanh tại KCN Quế Võ, Tiên Du, Từ Sơn. Giá minh bạch, đầy đủ hóa đơn VAT. Gọi 0971 491 174.", "category": "cuu-ho", "priority": "tier1", "area": ["Bắc Ninh"], "tags": ["xe cẩu gấp", "Bắc Ninh"], "keywords": {"primary": "xe cẩu gấp Bắc Ninh", "secondary": ["thuê cẩu gấp Bắc Ninh"], "lsi": ["KCN Quế Võ", "Từ Sơn"]}},
    {"id": 9, "slug": "xe-cau-gap-bac-giang", "title": "Xe Cẩu Gấp Bắc Giang — Phục Vụ KCN 24/7", "description": "Xe cẩu gấp tại Bắc Giang. Phục vụ KCN Việt Yên, Đình Trám, Song Khê. Cẩu 3.5T–100T. Gọi ngay 0971 491 174.", "category": "cuu-ho", "priority": "tier1", "area": ["Bắc Giang"], "tags": ["xe cẩu gấp", "Bắc Giang"], "keywords": {"primary": "xe cẩu gấp Bắc Giang", "secondary": ["thuê cẩu gấp Bắc Giang"], "lsi": ["KCN Đình Trám", "Việt Yên"]}},
    {"id": 10, "slug": "xe-cau-gap-thai-binh", "title": "Xe Cẩu Gấp Thái Bình — Điều Xe Nhanh Từ Hưng Yên", "description": "Cần xe cẩu gấp Thái Bình? Giang Khôi điều xe từ Hưng Yên, có mặt nhanh. KCN Tiền Hải, Thái Thụy. Gọi 0971 491 174.", "category": "cuu-ho", "priority": "tier1", "area": ["Thái Bình"], "tags": ["xe cẩu gấp", "Thái Bình"], "keywords": {"primary": "xe cẩu gấp Thái Bình", "secondary": ["thuê cẩu gấp Thái Bình"], "lsi": ["KCN Tiền Hải"]}},

    # --- Cẩu hàng nặng / công trình lớn ---
    {"id": 11, "slug": "thue-xe-cau-50-tan-bac-ninh", "title": "Thuê Xe Cẩu 50 Tấn Bắc Ninh — Cẩu Nặng Công Trình", "description": "Cho thuê xe cẩu 50 tấn tại Bắc Ninh. Phục vụ công trình lớn, lắp đặt kết cấu thép, cẩu dầm cầu. Giá từ 9.400.000đ/ca.", "category": "cong-nghiep", "priority": "tier1", "area": ["Bắc Ninh"], "tags": ["cẩu 50 tấn", "Bắc Ninh", "cẩu nặng"], "keywords": {"primary": "thuê xe cẩu 50 tấn Bắc Ninh", "secondary": ["xe cẩu 50 tấn Bắc Ninh"], "lsi": ["cẩu dầm cầu", "kết cấu thép"]}},
    {"id": 12, "slug": "thue-xe-cau-100-tan-ha-noi", "title": "Thuê Xe Cẩu 100 Tấn Hà Nội — Cẩu Siêu Trọng", "description": "Cho thuê xe cẩu 100 tấn tại Hà Nội. Cẩu dầm cầu, cẩu máy biến áp, lắp đặt thiết bị nặng. Giá từ 16.900.000đ/ca.", "category": "cong-nghiep", "priority": "tier1", "area": ["Hà Nội"], "tags": ["cẩu 100 tấn", "Hà Nội", "cẩu siêu trọng"], "keywords": {"primary": "thuê xe cẩu 100 tấn Hà Nội", "secondary": ["xe cẩu 100 tấn Hà Nội"], "lsi": ["cẩu siêu trọng", "máy biến áp"]}},
    {"id": 13, "slug": "cau-container-kcn-bac-ninh", "title": "Cẩu Container KCN Bắc Ninh — Nâng Hạ Chuyên Nghiệp", "description": "Dịch vụ cẩu container tại KCN Bắc Ninh. Nâng hạ container 20ft, 40ft. Phục vụ KCN Quế Võ, Tiên Du, Yên Phong.", "category": "cong-nghiep", "priority": "tier1", "area": ["Bắc Ninh"], "tags": ["cẩu container", "KCN", "Bắc Ninh"], "keywords": {"primary": "cẩu container KCN Bắc Ninh", "secondary": ["nâng hạ container Bắc Ninh"], "lsi": ["container 40ft", "KCN Quế Võ"]}},
    {"id": 14, "slug": "cau-may-moc-di-doi-xuong-bac-giang", "title": "Cẩu Máy Móc Di Dời Xưởng Bắc Giang — An Toàn, Chuyên Nghiệp", "description": "Dịch vụ cẩu máy móc di dời xưởng tại Bắc Giang. Cẩu máy CNC, máy ép, máy dập. Đội ngũ kinh nghiệm, an toàn tuyệt đối.", "category": "cong-nghiep", "priority": "tier1", "area": ["Bắc Giang"], "tags": ["cẩu máy móc", "di dời xưởng", "Bắc Giang"], "keywords": {"primary": "cẩu máy móc di dời xưởng Bắc Giang", "secondary": ["di chuyển máy CNC Bắc Giang"], "lsi": ["cẩu máy ép", "di dời nhà xưởng"]}},
    {"id": 15, "slug": "cau-hang-nang-cong-trinh-hung-yen", "title": "Cẩu Hàng Nặng Công Trình Hưng Yên — Đội Cẩu Chuyên Nghiệp", "description": "Dịch vụ cẩu hàng nặng cho công trình tại Hưng Yên. Cẩu dầm thép, kết cấu, thiết bị công nghiệp. Gọi 0971 491 174.", "category": "cong-nghiep", "priority": "tier1", "area": ["Hưng Yên"], "tags": ["cẩu hàng nặng", "công trình", "Hưng Yên"], "keywords": {"primary": "cẩu hàng nặng công trình Hưng Yên", "secondary": ["cẩu kết cấu thép Hưng Yên"], "lsi": ["dầm thép", "thiết bị công nghiệp"]}},

    # --- Cẩu KCN lớn ---
    {"id": 16, "slug": "xe-cau-kcn-pho-noi", "title": "Xe Cẩu KCN Phố Nối — Phục Vụ 3 KCN Lớn Nhất Hưng Yên", "description": "Dịch vụ xe cẩu tại KCN Phố Nối A, Phố Nối B, Thăng Long II. Có mặt 15 phút. Cẩu hàng, lắp đặt, di dời máy móc.", "category": "cong-nghiep", "priority": "tier1", "area": ["Hưng Yên"], "tags": ["xe cẩu KCN", "Phố Nối", "Hưng Yên"], "keywords": {"primary": "xe cẩu KCN Phố Nối", "secondary": ["cẩu hàng KCN Phố Nối A"], "lsi": ["KCN Thăng Long II", "lắp đặt máy"]}},
    {"id": 17, "slug": "xe-cau-kcn-que-vo-bac-ninh", "title": "Xe Cẩu KCN Quế Võ Bắc Ninh — Nhanh, Uy Tín", "description": "Cho thuê xe cẩu tại KCN Quế Võ, Bắc Ninh. Phục vụ nâng hạ hàng hóa, lắp đặt thiết bị nhà máy. Gọi 0971 491 174.", "category": "cong-nghiep", "priority": "tier1", "area": ["Bắc Ninh"], "tags": ["xe cẩu KCN", "Quế Võ", "Bắc Ninh"], "keywords": {"primary": "xe cẩu KCN Quế Võ Bắc Ninh", "secondary": ["cẩu hàng KCN Quế Võ"], "lsi": ["nhà máy Samsung", "nâng hạ thiết bị"]}},
    {"id": 18, "slug": "xe-cau-kcn-viet-yen-bac-giang", "title": "Xe Cẩu KCN Việt Yên Bắc Giang — Phục Vụ Nhà Máy FDI", "description": "Dịch vụ xe cẩu KCN Việt Yên, Bắc Giang. Phục vụ nhà máy Foxconn, Luxshare. Cẩu máy, thiết bị, container. 24/7.", "category": "cong-nghiep", "priority": "tier1", "area": ["Bắc Giang"], "tags": ["xe cẩu KCN", "Việt Yên", "Bắc Giang"], "keywords": {"primary": "xe cẩu KCN Việt Yên Bắc Giang", "secondary": ["cẩu hàng KCN Đình Trám"], "lsi": ["Foxconn", "Luxshare"]}},
    {"id": 19, "slug": "cau-container-40-feet-gia-re", "title": "Cẩu Container 40 Feet Giá Rẻ — Bảng Giá 2026", "description": "Giá cẩu container 40 feet mới nhất 2026. So sánh giá theo khu vực: Hưng Yên, Hà Nội, Bắc Ninh, Bắc Giang. Gọi báo giá chính xác.", "category": "cong-nghiep", "priority": "tier1", "area": ["Hưng Yên", "Hà Nội", "Bắc Ninh", "Bắc Giang"], "tags": ["cẩu container", "40 feet", "giá rẻ"], "keywords": {"primary": "cẩu container 40 feet giá rẻ", "secondary": ["giá cẩu container 40ft"], "lsi": ["nâng hạ container", "bãi container"]}},
    {"id": 20, "slug": "cau-may-cnc-di-doi", "title": "Cẩu Máy CNC Di Dời — Quy Trình An Toàn & Chi Phí", "description": "Hướng dẫn cẩu máy CNC di dời xưởng an toàn. Chi phí, quy trình, lưu ý quan trọng. Giang Khôi có kinh nghiệm 10 năm.", "category": "cong-nghiep", "priority": "tier1", "area": ["Hưng Yên", "Bắc Ninh", "Bắc Giang"], "tags": ["cẩu máy CNC", "di dời xưởng"], "keywords": {"primary": "cẩu máy CNC di dời", "secondary": ["di chuyển máy CNC an toàn"], "lsi": ["máy phay CNC", "máy tiện CNC"]}},

    # --- Cẩu gấp đêm / lễ Tết ---
    {"id": 21, "slug": "xe-cau-lam-dem-ha-noi", "title": "Xe Cẩu Làm Đêm Hà Nội — Phục Vụ Công Trình Ban Đêm", "description": "Cho thuê xe cẩu làm đêm tại Hà Nội. Phục vụ công trình nội đô, cẩu dầm cầu, lắp đặt thiết bị ban đêm. An toàn, chuyên nghiệp.", "category": "cuu-ho", "priority": "tier1", "area": ["Hà Nội"], "tags": ["xe cẩu đêm", "Hà Nội", "công trình đêm"], "keywords": {"primary": "xe cẩu làm đêm Hà Nội", "secondary": ["thuê cẩu ban đêm Hà Nội"], "lsi": ["giờ cấm tải", "nội đô Hà Nội"]}},
    {"id": 22, "slug": "xe-cau-ngay-le-tet", "title": "Xe Cẩu Ngày Lễ Tết — Phục Vụ 24/7 Không Nghỉ", "description": "Dịch vụ xe cẩu ngày lễ, Tết. Giang Khôi phục vụ 24/7 kể cả ngày nghỉ. Cứu hộ gấp, cẩu bồn nước, cẩu hàng.", "category": "cuu-ho", "priority": "tier1", "area": ["Hưng Yên", "Hà Nội", "Bắc Ninh"], "tags": ["xe cẩu Tết", "ngày lễ", "24/7"], "keywords": {"primary": "xe cẩu ngày lễ Tết", "secondary": ["thuê cẩu ngày nghỉ"], "lsi": ["cẩu cứu hộ Tết", "phục vụ 24/7"]}},

    # --- Cho thuê theo tải trọng + khu vực ---
    {"id": 23, "slug": "thue-xe-cau-25-tan-hung-yen", "title": "Thuê Xe Cẩu 25 Tấn Hưng Yên — Giá & Quy Trình", "description": "Cho thuê xe cẩu 25 tấn tại Hưng Yên. Phục vụ lắp đặt kết cấu, cẩu máy lớn. Giá từ 7.500.000đ/ca. Gọi 0971 491 174.", "category": "cong-nghiep", "priority": "tier1", "area": ["Hưng Yên"], "tags": ["cẩu 25 tấn", "Hưng Yên"], "keywords": {"primary": "thuê xe cẩu 25 tấn Hưng Yên", "secondary": ["xe cẩu 25 tấn Hưng Yên giá"], "lsi": ["cẩu kết cấu", "lắp đặt"]}},
    {"id": 24, "slug": "thue-xe-cau-15-tan-bac-giang", "title": "Thuê Xe Cẩu 15 Tấn Bắc Giang — KCN & Công Trình", "description": "Cho thuê xe cẩu 15 tấn Bắc Giang. Phục vụ KCN, xây dựng, lắp đặt. Giá từ 5.500.000đ/ca. Đầy đủ hóa đơn VAT. Gọi ngay!", "category": "cong-nghiep", "priority": "tier1", "area": ["Bắc Giang"], "tags": ["cẩu 15 tấn", "Bắc Giang"], "keywords": {"primary": "thuê xe cẩu 15 tấn Bắc Giang", "secondary": ["xe cẩu 15 tấn Bắc Giang"], "lsi": ["KCN Bắc Giang"]}},
    {"id": 25, "slug": "thue-xe-cau-10-tan-ha-noi", "title": "Thuê Xe Cẩu 10 Tấn Hà Nội — Đa Dụng, Linh Hoạt", "description": "Cho thuê xe cẩu 10 tấn Hà Nội. Cẩu container, máy nhỏ, vật liệu xây dựng. Giá từ 4.500.000đ/ca. Gọi 0971 491 174.", "category": "cong-nghiep", "priority": "tier1", "area": ["Hà Nội"], "tags": ["cẩu 10 tấn", "Hà Nội"], "keywords": {"primary": "thuê xe cẩu 10 tấn Hà Nội", "secondary": ["xe cẩu 10 tấn Hà Nội giá"], "lsi": ["cẩu container", "vật liệu"]}},
    {"id": 26, "slug": "thue-xe-cau-8-tan-thai-binh", "title": "Thuê Xe Cẩu 8 Tấn Thái Bình — Giá Tốt, Uy Tín", "description": "Cho thuê xe cẩu 8 tấn Thái Bình. Phục vụ xây dựng, cẩu bồn, container nhỏ. Giá từ 4.000.000đ/ca.", "category": "cong-nghiep", "priority": "tier1", "area": ["Thái Bình"], "tags": ["cẩu 8 tấn", "Thái Bình"], "keywords": {"primary": "thuê xe cẩu 8 tấn Thái Bình", "secondary": ["xe cẩu 8 tấn Thái Bình"], "lsi": ["cẩu bồn nước", "xây dựng"]}},
    {"id": 27, "slug": "cho-thue-xe-cau-theo-thang-hung-yen", "title": "Cho Thuê Xe Cẩu Theo Tháng Hưng Yên — Giá Tiết Kiệm", "description": "Cho thuê xe cẩu dài hạn theo tháng tại Hưng Yên. Giá ưu đãi cho KCN, công trình dài hạn. Từ 45 triệu/tháng.", "category": "cong-nghiep", "priority": "tier1", "area": ["Hưng Yên"], "tags": ["thuê theo tháng", "Hưng Yên", "dài hạn"], "keywords": {"primary": "cho thuê xe cẩu theo tháng Hưng Yên", "secondary": ["thuê cẩu dài hạn Hưng Yên"], "lsi": ["hợp đồng tháng", "KCN"]}},
    {"id": 28, "slug": "xe-cau-cho-thue-gia-re-hung-yen", "title": "Xe Cẩu Cho Thuê Giá Rẻ Hưng Yên — Bảng Giá 2026", "description": "Thuê xe cẩu giá rẻ tại Hưng Yên. Bảng giá cập nhật tháng 6/2026. Cẩu 3.5T–100T. Đầy đủ hóa đơn. Gọi 0971 491 174.", "category": "bang-gia", "priority": "tier1", "area": ["Hưng Yên"], "tags": ["giá rẻ", "Hưng Yên", "bảng giá"], "keywords": {"primary": "xe cẩu cho thuê giá rẻ Hưng Yên", "secondary": ["thuê cẩu giá rẻ Mỹ Hào"], "lsi": ["bảng giá 2026", "giá cạnh tranh"]}},
    {"id": 29, "slug": "xe-cau-cuu-ho-duong-cao-toc", "title": "Xe Cẩu Cứu Hộ Đường Cao Tốc Hà Nội – Hải Phòng", "description": "Dịch vụ cẩu cứu hộ trên đường cao tốc Hà Nội – Hải Phòng. Xử lý xe lật, container rơi, tai nạn giao thông. Có mặt nhanh.", "category": "cuu-ho", "priority": "tier1", "area": ["Hưng Yên", "Hà Nội"], "tags": ["cứu hộ cao tốc", "Hà Nội – Hải Phòng"], "keywords": {"primary": "xe cẩu cứu hộ đường cao tốc", "secondary": ["cứu hộ cao tốc Hà Nội Hải Phòng"], "lsi": ["tai nạn cao tốc", "container rơi"]}},
    {"id": 30, "slug": "cau-cuu-ho-container-roi", "title": "Cẩu Cứu Hộ Container Rơi — Xử Lý Nhanh, An Toàn", "description": "Dịch vụ cẩu cứu hộ container rơi trên đường. Xử lý nhanh, an toàn, chuyên nghiệp. Phục vụ Hưng Yên, Hà Nội, Bắc Ninh.", "category": "cuu-ho", "priority": "tier1", "area": ["Hưng Yên", "Hà Nội", "Bắc Ninh"], "tags": ["cứu hộ container", "container rơi"], "keywords": {"primary": "cẩu cứu hộ container rơi", "secondary": ["container rơi đường"], "lsi": ["tai nạn container", "xử lý sự cố"]}},

    # ═══════════════════════════════════════════════════════════════
    # TIER 2: HIGH VALUE — Dân dụng lợi nhuận tốt (30 bài)
    # ═══════════════════════════════════════════════════════════════

    {"id": 31, "slug": "gia-cau-bon-nuoc-len-mai-nha-pho", "title": "Giá Cẩu Bồn Nước Lên Mái Nhà Phố — Chi Phí & Quy Trình 2026", "description": "Giá cẩu bồn nước inox lên mái nhà phố 2026. Chi phí từ 800.000–2.000.000đ tùy tầng. Quy trình an toàn, nhanh gọn.", "category": "dan-dung", "priority": "tier2", "area": ["Hưng Yên", "Hà Nội"], "tags": ["cẩu bồn nước", "nhà phố", "giá"], "keywords": {"primary": "giá cẩu bồn nước lên mái", "secondary": ["chi phí cẩu bồn nước"], "lsi": ["bồn inox", "nhà phố"]}},
    {"id": 32, "slug": "cau-vat-lieu-xay-nha-hung-yen", "title": "Cẩu Vật Liệu Xây Nhà Hưng Yên — Tiết Kiệm Thời Gian", "description": "Dịch vụ cẩu vật liệu xây nhà tại Hưng Yên. Cẩu gạch, thép, xi măng lên tầng cao. Nhanh gọn, giá hợp lý.", "category": "dan-dung", "priority": "tier2", "area": ["Hưng Yên"], "tags": ["vật liệu xây dựng", "Hưng Yên"], "keywords": {"primary": "cẩu vật liệu xây nhà Hưng Yên", "secondary": ["cẩu gạch lên tầng Hưng Yên"], "lsi": ["thép xây nhà", "xi măng"]}},
    {"id": 33, "slug": "thue-xe-cau-xay-nha-ha-noi", "title": "Thuê Xe Cẩu Xây Nhà Hà Nội — Giá & Dịch Vụ 2026", "description": "Thuê xe cẩu phục vụ xây nhà tại Hà Nội. Cẩu vật liệu, bồn nước, mái tôn. Giá từ 2.800.000đ/ca. Đầy đủ hóa đơn.", "category": "dan-dung", "priority": "tier2", "area": ["Hà Nội"], "tags": ["xe cẩu xây nhà", "Hà Nội"], "keywords": {"primary": "thuê xe cẩu xây nhà Hà Nội", "secondary": ["xe cẩu cho xây dựng Hà Nội"], "lsi": ["vật liệu xây dựng", "mái tôn"]}},
    {"id": 34, "slug": "cau-mai-ton-khung-keo-gia-bao-nhieu", "title": "Cẩu Mái Tôn Khung Kèo Giá Bao Nhiêu? — Bảng Giá 2026", "description": "Giá cẩu mái tôn, khung kèo thép 2026. Chi phí theo khối lượng và tầng cao. So sánh giá các khu vực. Gọi báo giá.", "category": "dan-dung", "priority": "tier2", "area": ["Hưng Yên", "Hà Nội", "Bắc Ninh"], "tags": ["mái tôn", "khung kèo", "giá"], "keywords": {"primary": "cẩu mái tôn khung kèo giá bao nhiêu", "secondary": ["giá cẩu mái tôn"], "lsi": ["khung kèo thép", "mái nhà xưởng"]}},
    {"id": 35, "slug": "cau-cay-canh-biet-thu-ha-noi", "title": "Cẩu Cây Cảnh Biệt Thự Hà Nội — Chuyên Nghiệp, An Toàn", "description": "Dịch vụ cẩu cây cảnh biệt thự tại Hà Nội. Cẩu cây lớn, cây bonsai quý. An toàn tuyệt đối cho cây và công trình.", "category": "dan-dung", "priority": "tier2", "area": ["Hà Nội"], "tags": ["cẩu cây cảnh", "biệt thự", "Hà Nội"], "keywords": {"primary": "cẩu cây cảnh biệt thự Hà Nội", "secondary": ["cẩu cây lớn Hà Nội"], "lsi": ["cây bonsai", "Ecopark"]}},
    {"id": 36, "slug": "cau-bon-nuoc-inox-1000-lit", "title": "Cẩu Bồn Nước Inox 1000 Lít Lên Mái — Giá & Lưu Ý", "description": "Hướng dẫn cẩu bồn nước inox 1000 lít lên mái nhà. Chi phí, quy trình, lưu ý an toàn. Giang Khôi phục vụ chuyên nghiệp.", "category": "dan-dung", "priority": "tier2", "area": ["Hưng Yên", "Hà Nội"], "tags": ["bồn nước inox", "1000 lít", "lên mái"], "keywords": {"primary": "cẩu bồn nước inox 1000 lít lên mái", "secondary": ["giá cẩu bồn 1000L"], "lsi": ["bồn Tân Á", "bồn Sơn Hà"]}},
    {"id": 37, "slug": "cau-cay-canh-hung-yen", "title": "Cẩu Cây Cảnh Hưng Yên — Cẩu Cây Lớn Vào Sân Vườn", "description": "Dịch vụ cẩu cây cảnh tại Hưng Yên. Cẩu cây sanh, si, lộc vừng vào sân vườn. An toàn, không hư hại cây.", "category": "dan-dung", "priority": "tier2", "area": ["Hưng Yên"], "tags": ["cẩu cây cảnh", "Hưng Yên"], "keywords": {"primary": "cẩu cây cảnh Hưng Yên", "secondary": ["cẩu cây lộc vừng Hưng Yên"], "lsi": ["cây sanh", "sân vườn"]}},
    {"id": 38, "slug": "cau-bon-nuoc-bac-ninh", "title": "Cẩu Bồn Nước Bắc Ninh — Giá Rẻ, Nhanh Chóng", "description": "Dịch vụ cẩu bồn nước lên mái tại Bắc Ninh. Bồn 500L–3000L. Giá từ 800.000đ. An toàn, bảo hành.", "category": "dan-dung", "priority": "tier2", "area": ["Bắc Ninh"], "tags": ["cẩu bồn nước", "Bắc Ninh"], "keywords": {"primary": "cẩu bồn nước Bắc Ninh", "secondary": ["giá cẩu bồn nước Bắc Ninh"], "lsi": ["bồn inox", "mái nhà"]}},
    {"id": 39, "slug": "cau-vat-lieu-xay-dung-bac-giang", "title": "Cẩu Vật Liệu Xây Dựng Bắc Giang — Phục Vụ Công Trình", "description": "Dịch vụ cẩu vật liệu xây dựng tại Bắc Giang. Cẩu thép, bê tông, gạch lên tầng cao. Phục vụ nhanh.", "category": "dan-dung", "priority": "tier2", "area": ["Bắc Giang"], "tags": ["vật liệu xây dựng", "Bắc Giang"], "keywords": {"primary": "cẩu vật liệu xây dựng Bắc Giang", "secondary": ["cẩu thép xây dựng Bắc Giang"], "lsi": ["bê tông", "tầng cao"]}},
    {"id": 40, "slug": "cau-mai-ton-nha-xuong-hung-yen", "title": "Cẩu Mái Tôn Nhà Xưởng Hưng Yên — Lắp Đặt Chuyên Nghiệp", "description": "Dịch vụ cẩu mái tôn nhà xưởng tại Hưng Yên. Lắp mái tôn, khung kèo thép. Đội cẩu kinh nghiệm.", "category": "dan-dung", "priority": "tier2", "area": ["Hưng Yên"], "tags": ["mái tôn nhà xưởng", "Hưng Yên"], "keywords": {"primary": "cẩu mái tôn nhà xưởng Hưng Yên", "secondary": ["lắp mái tôn Hưng Yên"], "lsi": ["khung kèo thép", "nhà xưởng"]}},
    {"id": 41, "slug": "thue-xe-cau-5-tan-hung-yen", "title": "Thuê Xe Cẩu 5 Tấn Hưng Yên — Nhỏ Gọn, Giá Tốt", "description": "Cho thuê xe cẩu 5 tấn Hưng Yên. Phù hợp cẩu bồn nước, cây cảnh, vật liệu nhẹ. Giá từ 2.800.000đ/ca.", "category": "dan-dung", "priority": "tier2", "area": ["Hưng Yên"], "tags": ["cẩu 5 tấn", "Hưng Yên"], "keywords": {"primary": "thuê xe cẩu 5 tấn Hưng Yên", "secondary": ["xe cẩu 5 tấn Hưng Yên giá"], "lsi": ["cẩu nhẹ", "hẻm nhỏ"]}},
    {"id": 42, "slug": "thue-xe-cau-3-5-tan-ha-noi", "title": "Thuê Xe Cẩu 3.5 Tấn Hà Nội — Vào Hẻm Nhỏ Dễ Dàng", "description": "Cho thuê xe cẩu 3.5 tấn tại Hà Nội. Xe nhỏ gọn, vào được hẻm nhỏ. Cẩu bồn nước, cây cảnh. Giá từ 2.800.000đ/ca.", "category": "dan-dung", "priority": "tier2", "area": ["Hà Nội"], "tags": ["cẩu 3.5 tấn", "Hà Nội", "hẻm nhỏ"], "keywords": {"primary": "thuê xe cẩu 3.5 tấn Hà Nội", "secondary": ["xe cẩu nhỏ Hà Nội"], "lsi": ["hẻm nhỏ", "ngõ ngách"]}},
    {"id": 43, "slug": "cau-bon-nuoc-thai-binh", "title": "Cẩu Bồn Nước Thái Bình — Giá & Dịch Vụ 2026", "description": "Dịch vụ cẩu bồn nước lên mái tại Thái Bình. Phục vụ nhà dân, công trình. Giá hợp lý, an toàn.", "category": "dan-dung", "priority": "tier2", "area": ["Thái Bình"], "tags": ["cẩu bồn nước", "Thái Bình"], "keywords": {"primary": "cẩu bồn nước Thái Bình", "secondary": ["giá cẩu bồn Thái Bình"], "lsi": ["bồn inox", "mái nhà"]}},
    {"id": 44, "slug": "cau-cay-canh-bac-ninh", "title": "Cẩu Cây Cảnh Bắc Ninh — An Toàn, Giá Hợp Lý", "description": "Dịch vụ cẩu cây cảnh tại Bắc Ninh. Cẩu cây vào sân biệt thự, resort, nhà hàng. Bảo vệ cây an toàn.", "category": "dan-dung", "priority": "tier2", "area": ["Bắc Ninh"], "tags": ["cẩu cây cảnh", "Bắc Ninh"], "keywords": {"primary": "cẩu cây cảnh Bắc Ninh", "secondary": ["cẩu cây lớn Bắc Ninh"], "lsi": ["biệt thự", "sân vườn"]}},
    {"id": 45, "slug": "cau-mai-ton-bac-giang", "title": "Cẩu Mái Tôn Bắc Giang — Lắp Đặt Nhà Xưởng & Dân Dụng", "description": "Dịch vụ cẩu mái tôn tại Bắc Giang. Phục vụ nhà xưởng, nhà dân. Cẩu khung kèo thép, panel. Giá tốt.", "category": "dan-dung", "priority": "tier2", "area": ["Bắc Giang"], "tags": ["mái tôn", "Bắc Giang"], "keywords": {"primary": "cẩu mái tôn Bắc Giang", "secondary": ["lắp mái tôn Bắc Giang"], "lsi": ["khung kèo", "panel"]}},
    {"id": 46, "slug": "cau-vat-lieu-xay-nha-thai-binh", "title": "Cẩu Vật Liệu Xây Nhà Thái Bình — Nhanh, Tiện", "description": "Dịch vụ cẩu vật liệu xây nhà Thái Bình. Cẩu thép, gạch, bê tông lên tầng cao. Giá hợp lý.", "category": "dan-dung", "priority": "tier2", "area": ["Thái Bình"], "tags": ["vật liệu xây dựng", "Thái Bình"], "keywords": {"primary": "cẩu vật liệu xây nhà Thái Bình", "secondary": ["cẩu gạch Thái Bình"], "lsi": ["xây nhà", "tầng cao"]}},
    {"id": 47, "slug": "xe-cau-van-lam-hung-yen", "title": "Xe Cẩu Văn Lâm Hưng Yên — Có Mặt 20 Phút", "description": "Dịch vụ xe cẩu tại Văn Lâm, Hưng Yên. Có mặt trong 20 phút. Phục vụ KCN Như Quỳnh, khu đô thị mới.", "category": "khu-vuc", "priority": "tier2", "area": ["Hưng Yên"], "tags": ["Văn Lâm", "Hưng Yên"], "keywords": {"primary": "xe cẩu Văn Lâm Hưng Yên", "secondary": ["thuê cẩu Văn Lâm"], "lsi": ["KCN Như Quỳnh", "khu đô thị"]}},
    {"id": 48, "slug": "xe-cau-yen-my-hung-yen", "title": "Xe Cẩu Yên Mỹ Hưng Yên — Phục Vụ KCN & Dân Sinh", "description": "Dịch vụ xe cẩu Yên Mỹ, Hưng Yên. Phục vụ KCN Yên Mỹ I, II. Cẩu hàng, máy móc, vật liệu. 20 phút có mặt.", "category": "khu-vuc", "priority": "tier2", "area": ["Hưng Yên"], "tags": ["Yên Mỹ", "Hưng Yên"], "keywords": {"primary": "xe cẩu Yên Mỹ Hưng Yên", "secondary": ["thuê cẩu Yên Mỹ"], "lsi": ["KCN Yên Mỹ"]}},
    {"id": 49, "slug": "xe-cau-gia-lam-ha-noi", "title": "Xe Cẩu Gia Lâm Hà Nội — Phục Vụ Nhanh Từ Hưng Yên", "description": "Dịch vụ xe cẩu tại Gia Lâm, Hà Nội. Điều xe nhanh từ Mỹ Hào. Phục vụ KCN, xây dựng, cứu hộ.", "category": "khu-vuc", "priority": "tier2", "area": ["Hà Nội"], "tags": ["Gia Lâm", "Hà Nội"], "keywords": {"primary": "xe cẩu Gia Lâm Hà Nội", "secondary": ["thuê cẩu Gia Lâm"], "lsi": ["Long Biên", "KCN Sài Đồng"]}},
    {"id": 50, "slug": "xe-cau-tu-son-bac-ninh", "title": "Xe Cẩu Từ Sơn Bắc Ninh — Phục Vụ Đô Thị & KCN", "description": "Dịch vụ xe cẩu Từ Sơn, Bắc Ninh. Phục vụ khu đô thị, công trình xây dựng, KCN. Gọi 0971 491 174.", "category": "khu-vuc", "priority": "tier2", "area": ["Bắc Ninh"], "tags": ["Từ Sơn", "Bắc Ninh"], "keywords": {"primary": "xe cẩu Từ Sơn Bắc Ninh", "secondary": ["thuê cẩu Từ Sơn"], "lsi": ["khu đô thị", "VSIP"]}},
    {"id": 51, "slug": "cau-container-20-feet", "title": "Cẩu Container 20 Feet — Giá & Quy Trình Chi Tiết", "description": "Hướng dẫn cẩu container 20 feet. Giá bao nhiêu? Cần xe cẩu mấy tấn? Quy trình an toàn. Cập nhật 2026.", "category": "cong-nghiep", "priority": "tier2", "area": ["Hưng Yên", "Hà Nội", "Bắc Ninh"], "tags": ["container 20 feet", "giá"], "keywords": {"primary": "cẩu container 20 feet giá", "secondary": ["giá cẩu container 20ft"], "lsi": ["xe cẩu container", "bãi container"]}},
    {"id": 52, "slug": "cau-may-ep-nhua-di-doi", "title": "Cẩu Máy Ép Nhựa Di Dời — Lưu Ý & Chi Phí", "description": "Hướng dẫn cẩu máy ép nhựa di dời xưởng. Trọng lượng, kích thước, loại xe cẩu phù hợp. Chi phí tham khảo.", "category": "cong-nghiep", "priority": "tier2", "area": ["Hưng Yên", "Bắc Ninh", "Bắc Giang"], "tags": ["máy ép nhựa", "di dời"], "keywords": {"primary": "cẩu máy ép nhựa di dời", "secondary": ["di chuyển máy ép nhựa"], "lsi": ["máy ép phun", "nhà xưởng"]}},
    {"id": 53, "slug": "xe-cau-ecopark-van-giang", "title": "Xe Cẩu Ecopark Văn Giang — Cẩu Cây, Bồn Nước, Nội Thất", "description": "Dịch vụ xe cẩu tại khu đô thị Ecopark, Văn Giang. Cẩu cây cảnh, bồn nước, nội thất biệt thự. An toàn, chuyên nghiệp.", "category": "khu-vuc", "priority": "tier2", "area": ["Hưng Yên"], "tags": ["Ecopark", "Văn Giang", "biệt thự"], "keywords": {"primary": "xe cẩu Ecopark Văn Giang", "secondary": ["cẩu cây cảnh Ecopark"], "lsi": ["biệt thự", "Dream City"]}},
    {"id": 54, "slug": "cau-bon-nuoc-500-lit-len-mai", "title": "Cẩu Bồn Nước 500 Lít Lên Mái — Giá Chỉ Từ 800.000đ", "description": "Chi phí cẩu bồn nước 500 lít lên mái nhà. Giá từ 800.000đ tùy tầng cao. Quy trình an toàn, nhanh gọn.", "category": "dan-dung", "priority": "tier2", "area": ["Hưng Yên", "Hà Nội"], "tags": ["bồn nước", "500 lít", "giá"], "keywords": {"primary": "cẩu bồn nước 500 lít lên mái giá", "secondary": ["giá cẩu bồn 500L"], "lsi": ["bồn Tân Á", "tầng 3"]}},
    {"id": 55, "slug": "cau-cay-loc-vung-lon", "title": "Cẩu Cây Lộc Vừng Lớn Vào Sân — Hướng Dẫn Chi Tiết", "description": "Hướng dẫn cẩu cây lộc vừng lớn vào sân vườn. Kỹ thuật buộc cây, chọn xe cẩu phù hợp. Bảo vệ rễ an toàn.", "category": "dan-dung", "priority": "tier2", "area": ["Hưng Yên", "Hà Nội"], "tags": ["cây lộc vừng", "cẩu cây lớn"], "keywords": {"primary": "cẩu cây lộc vừng lớn", "secondary": ["cẩu cây cảnh lớn vào sân"], "lsi": ["buộc cây", "bảo vệ rễ"]}},
    {"id": 56, "slug": "xe-cau-an-thi-hung-yen", "title": "Xe Cẩu Ân Thi Hưng Yên — Phục Vụ Nông Thôn & Công Trình", "description": "Dịch vụ xe cẩu tại Ân Thi, Hưng Yên. Phục vụ xây dựng nông thôn mới, công trình, KCN. 25 phút có mặt.", "category": "khu-vuc", "priority": "tier2", "area": ["Hưng Yên"], "tags": ["Ân Thi", "Hưng Yên"], "keywords": {"primary": "xe cẩu Ân Thi Hưng Yên", "secondary": ["thuê cẩu Ân Thi"], "lsi": ["nông thôn mới", "KCN Ân Thi"]}},
    {"id": 57, "slug": "xe-cau-khoai-chau-hung-yen", "title": "Xe Cẩu Khoái Châu Hưng Yên — Hỗ Trợ Xây Dựng Hạ Tầng", "description": "Dịch vụ xe cẩu Khoái Châu, Hưng Yên. Phục vụ xây cầu, đường, công trình giao thông. 30 phút có mặt.", "category": "khu-vuc", "priority": "tier2", "area": ["Hưng Yên"], "tags": ["Khoái Châu", "Hưng Yên"], "keywords": {"primary": "xe cẩu Khoái Châu Hưng Yên", "secondary": ["thuê cẩu Khoái Châu"], "lsi": ["xây cầu", "hạ tầng"]}},
    {"id": 58, "slug": "xe-cau-tp-hung-yen", "title": "Xe Cẩu TP Hưng Yên — Phục Vụ Đô Thị Hóa", "description": "Dịch vụ xe cẩu tại TP Hưng Yên. Phục vụ xây dựng chung cư, trung tâm thương mại, nhà phố. 30 phút có mặt.", "category": "khu-vuc", "priority": "tier2", "area": ["Hưng Yên"], "tags": ["TP Hưng Yên"], "keywords": {"primary": "xe cẩu TP Hưng Yên", "secondary": ["thuê cẩu TP Hưng Yên"], "lsi": ["chung cư", "đô thị hóa"]}},
    {"id": 59, "slug": "cau-thep-hinh-xay-dung", "title": "Cẩu Thép Hình Xây Dựng — Kỹ Thuật & Chi Phí", "description": "Dịch vụ cẩu thép hình (I, H, U) xây dựng. Kỹ thuật nâng hạ an toàn, chọn xe cẩu phù hợp. Chi phí tham khảo.", "category": "dan-dung", "priority": "tier2", "area": ["Hưng Yên", "Hà Nội", "Bắc Ninh"], "tags": ["thép hình", "xây dựng"], "keywords": {"primary": "cẩu thép hình xây dựng", "secondary": ["cẩu thép I H U"], "lsi": ["kết cấu thép", "nâng hạ"]}},
    {"id": 60, "slug": "cau-be-tong-duc-san-xay-nha", "title": "Cẩu Bê Tông Đúc Sẵn — Panel, Dầm, Cột Xây Nhà", "description": "Dịch vụ cẩu bê tông đúc sẵn: panel tường, dầm, cột. Phục vụ xây nhà nhanh. Kỹ thuật cẩu an toàn.", "category": "dan-dung", "priority": "tier2", "area": ["Hưng Yên", "Hà Nội"], "tags": ["bê tông đúc sẵn", "panel"], "keywords": {"primary": "cẩu bê tông đúc sẵn xây nhà", "secondary": ["cẩu panel bê tông"], "lsi": ["dầm bê tông", "nhà lắp ghép"]}},

    # ═══════════════════════════════════════════════════════════════
    # TIER 3: SEO BALANCE — Long-tail + Authority (25 bài)
    # ═══════════════════════════════════════════════════════════════

    {"id": 61, "slug": "bang-gia-thue-xe-cau-2026", "title": "Bảng Giá Thuê Xe Cẩu 2026 — Cập Nhật Mới Nhất Tháng 6", "description": "Bảng giá thuê xe cẩu 3.5T–100T mới nhất 2026. So sánh giá theo khu vực, tải trọng, thời gian thuê. Cập nhật tháng 6.", "category": "bang-gia", "priority": "tier3", "area": ["Hưng Yên", "Hà Nội", "Bắc Ninh", "Bắc Giang", "Thái Bình"], "tags": ["bảng giá", "2026"], "keywords": {"primary": "bảng giá thuê xe cẩu 2026", "secondary": ["giá xe cẩu 2026", "thuê cẩu bao nhiêu tiền"], "lsi": ["giá theo tấn", "giá theo ca"]}},
    {"id": 62, "slug": "cach-chon-tai-trong-xe-cau-phu-hop", "title": "Cách Chọn Tải Trọng Xe Cẩu Phù Hợp Công Việc", "description": "Hướng dẫn chọn xe cẩu phù hợp: 3.5T, 5T, 8T, 10T, 15T, 25T, 50T, 100T. Mỗi tải trọng dùng cho việc gì? Bảng so sánh chi tiết.", "category": "huong-dan", "priority": "tier3", "area": [], "tags": ["chọn xe cẩu", "tải trọng", "hướng dẫn"], "keywords": {"primary": "cách chọn tải trọng xe cẩu", "secondary": ["xe cẩu bao nhiêu tấn", "chọn cẩu nào"], "lsi": ["tải trọng nâng", "tầm với"]}},
    {"id": 63, "slug": "quy-trinh-thue-xe-cau-an-toan-7-buoc", "title": "Quy Trình Thuê Xe Cẩu An Toàn — 7 Bước Từ A-Z", "description": "7 bước thuê xe cẩu an toàn, đúng cách. Từ xác định nhu cầu → liên hệ → báo giá → thi công → nghiệm thu. Kinh nghiệm thực tế.", "category": "huong-dan", "priority": "tier3", "area": [], "tags": ["quy trình", "thuê xe cẩu", "an toàn"], "keywords": {"primary": "quy trình thuê xe cẩu an toàn", "secondary": ["cách thuê xe cẩu", "thuê cẩu thế nào"], "lsi": ["hợp đồng", "nghiệm thu"]}},
    {"id": 64, "slug": "so-sanh-xe-cau-kato-kanglim-tadano", "title": "So Sánh Xe Cẩu Kato vs Kanglim vs Tadano — Nên Chọn Hãng Nào?", "description": "So sánh 3 hãng xe cẩu phổ biến: Kato (Nhật), Kanglim (Hàn), Tadano (Nhật). Ưu nhược điểm, giá thuê, tải trọng.", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["Kato", "Kanglim", "Tadano", "so sánh"], "keywords": {"primary": "so sánh xe cẩu Kato Kanglim Tadano", "secondary": ["xe cẩu hãng nào tốt"], "lsi": ["cẩu Nhật", "cẩu Hàn"]}},
    {"id": 65, "slug": "top-5-loi-khi-thue-xe-cau", "title": "Top 5 Lỗi Khi Thuê Xe Cẩu Khiến Giá Đội Lên 30%", "description": "5 lỗi phổ biến khi thuê xe cẩu: chọn sai tải trọng, không khảo sát hiện trường, thiếu giấy phép... và cách tránh.", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["lỗi phổ biến", "tiết kiệm", "kinh nghiệm"], "keywords": {"primary": "lỗi khi thuê xe cẩu", "secondary": ["sai lầm thuê cẩu"], "lsi": ["giá đội", "phát sinh"]}},
    {"id": 66, "slug": "an-toan-lao-dong-van-hanh-xe-cau", "title": "An Toàn Lao Động Khi Vận Hành Xe Cẩu — 10 Quy Tắc Vàng", "description": "10 quy tắc an toàn lao động khi vận hành xe cẩu. Từ kiểm tra thiết bị → khu vực an toàn → tín hiệu → thời tiết.", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["an toàn lao động", "vận hành", "quy tắc"], "keywords": {"primary": "an toàn lao động vận hành xe cẩu", "secondary": ["quy tắc an toàn cẩu"], "lsi": ["kiểm tra thiết bị", "tín hiệu"]}},
    {"id": 67, "slug": "xe-cau-la-gi-cac-loai-xe-cau", "title": "Xe Cẩu Là Gì? Các Loại Xe Cẩu Phổ Biến Tại Việt Nam", "description": "Tìm hiểu xe cẩu là gì, có mấy loại. Cẩu bánh lốp, cẩu bánh xích, cẩu tháp, cẩu tự hành. So sánh ưu nhược điểm.", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["xe cẩu", "các loại", "kiến thức"], "keywords": {"primary": "xe cẩu là gì các loại xe cẩu", "secondary": ["xe cẩu có mấy loại"], "lsi": ["cẩu bánh lốp", "cẩu bánh xích"]}},
    {"id": 68, "slug": "gia-thue-xe-cau-theo-gio", "title": "Giá Thuê Xe Cẩu Theo Giờ — Khi Nào Thuê Giờ Có Lợi?", "description": "Bảng giá thuê xe cẩu theo giờ 2026. Khi nào nên thuê giờ thay vì thuê ca? So sánh chi phí và lời khuyên.", "category": "bang-gia", "priority": "tier3", "area": ["Hưng Yên", "Hà Nội"], "tags": ["giá theo giờ", "so sánh"], "keywords": {"primary": "giá thuê xe cẩu theo giờ", "secondary": ["thuê cẩu theo giờ bao nhiêu"], "lsi": ["thuê ca", "tiết kiệm"]}},
    {"id": 69, "slug": "gia-cau-cuu-ho-xe-tai-lat-bao-nhieu", "title": "Giá Cẩu Cứu Hộ Xe Tải Lật Bao Nhiêu? — Bảng Giá 2026", "description": "Chi phí cẩu cứu hộ xe tải lật 2026. Giá phụ thuộc vào tải trọng xe, vị trí, thời gian. Bảng giá tham khảo chi tiết.", "category": "bang-gia", "priority": "tier3", "area": ["Hưng Yên", "Hà Nội"], "tags": ["giá cứu hộ", "xe tải lật"], "keywords": {"primary": "giá cẩu cứu hộ xe tải lật", "secondary": ["chi phí cứu hộ xe lật"], "lsi": ["tải trọng", "ban đêm"]}},
    {"id": 70, "slug": "cau-cay-canh-gia-bao-nhieu-luu-y", "title": "Cẩu Cây Cảnh Giá Bao Nhiêu? — Chi Phí & Lưu Ý Quan Trọng", "description": "Giá cẩu cây cảnh 2026: từ 500.000–5.000.000đ tùy kích thước cây và vị trí. Lưu ý bảo vệ cây khi cẩu.", "category": "bang-gia", "priority": "tier3", "area": [], "tags": ["cẩu cây cảnh", "giá", "lưu ý"], "keywords": {"primary": "cẩu cây cảnh giá bao nhiêu", "secondary": ["chi phí cẩu cây cảnh"], "lsi": ["cây lớn", "bảo vệ rễ"]}},
    {"id": 71, "slug": "khi-nao-can-thue-xe-cau", "title": "Khi Nào Cần Thuê Xe Cẩu? — 8 Tình Huống Phổ Biến", "description": "8 tình huống bạn cần thuê xe cẩu: xây nhà, lắp bồn nước, di dời máy, cứu hộ... Mỗi tình huống cần xe cẩu loại nào?", "category": "huong-dan", "priority": "tier3", "area": [], "tags": ["khi nào thuê", "tình huống"], "keywords": {"primary": "khi nào cần thuê xe cẩu", "secondary": ["lúc nào thuê cẩu"], "lsi": ["xây nhà", "di dời"]}},
    {"id": 72, "slug": "xe-cau-tu-hanh-la-gi", "title": "Xe Cẩu Tự Hành Là Gì? — Ưu Điểm & Khi Nào Dùng", "description": "Tìm hiểu xe cẩu tự hành (truck crane). Ưu điểm: di chuyển linh hoạt, không cần rơ moóc. Khi nào nên dùng cẩu tự hành?", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["cẩu tự hành", "kiến thức"], "keywords": {"primary": "xe cẩu tự hành là gì", "secondary": ["truck crane"], "lsi": ["cẩu bánh lốp", "di chuyển"]}},
    {"id": 73, "slug": "tam-voi-xe-cau-la-gi", "title": "Tầm Với Xe Cẩu Là Gì? — Cách Tính & Bảng Tra Cứu", "description": "Tầm với (boom reach) xe cẩu là gì? Cách tính tầm với phù hợp công việc. Bảng tra cứu tầm với theo tải trọng.", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["tầm với", "boom reach", "kỹ thuật"], "keywords": {"primary": "tầm với xe cẩu là gì", "secondary": ["cách tính tầm với cẩu"], "lsi": ["boom", "nâng cao"]}},
    {"id": 74, "slug": "giay-phep-van-hanh-xe-cau", "title": "Giấy Phép Vận Hành Xe Cẩu — Quy Định & Cách Xin", "description": "Quy định về giấy phép vận hành xe cẩu tại Việt Nam. Ai cần giấy phép? Hồ sơ gồm những gì? Nơi đào tạo.", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["giấy phép", "vận hành", "quy định"], "keywords": {"primary": "giấy phép vận hành xe cẩu", "secondary": ["bằng lái xe cẩu"], "lsi": ["đào tạo", "chứng chỉ"]}},
    {"id": 75, "slug": "xe-cau-banh-xich-vs-banh-lop", "title": "Xe Cẩu Bánh Xích vs Bánh Lốp — Chọn Loại Nào?", "description": "So sánh xe cẩu bánh xích và bánh lốp. Ưu nhược điểm, khi nào dùng loại nào? Giá thuê khác nhau thế nào?", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["bánh xích", "bánh lốp", "so sánh"], "keywords": {"primary": "xe cẩu bánh xích vs bánh lốp", "secondary": ["cẩu bánh xích hay bánh lốp"], "lsi": ["crawler crane", "mobile crane"]}},
    {"id": 76, "slug": "chi-phi-van-chuyen-xe-cau", "title": "Chi Phí Vận Chuyển Xe Cẩu — Yếu Tố Ảnh Hưởng Giá", "description": "Các yếu tố ảnh hưởng chi phí vận chuyển xe cẩu: khoảng cách, tải trọng, đường xá. Cách tính giá minh bạch.", "category": "bang-gia", "priority": "tier3", "area": [], "tags": ["chi phí", "vận chuyển", "giá"], "keywords": {"primary": "chi phí vận chuyển xe cẩu", "secondary": ["phí di chuyển cẩu"], "lsi": ["khoảng cách", "cầu đường"]}},
    {"id": 77, "slug": "cau-dem-gia-cao-hon-bao-nhieu", "title": "Cẩu Đêm Giá Cao Hơn Bao Nhiêu? — So Sánh Giá Ngày vs Đêm", "description": "So sánh giá thuê xe cẩu ngày và đêm. Cẩu đêm tăng 15-30%. Khi nào phải cẩu đêm? Cách tiết kiệm chi phí.", "category": "bang-gia", "priority": "tier3", "area": [], "tags": ["cẩu đêm", "giá", "so sánh"], "keywords": {"primary": "cẩu đêm giá cao hơn bao nhiêu", "secondary": ["giá cẩu ban đêm"], "lsi": ["phụ phí đêm", "giờ cấm tải"]}},
    {"id": 78, "slug": "thue-xe-cau-co-can-hop-dong-khong", "title": "Thuê Xe Cẩu Có Cần Hợp Đồng Không? — Lời Khuyên", "description": "Có cần ký hợp đồng khi thuê xe cẩu? Khi nào bắt buộc? Nội dung hợp đồng gồm gì? Lời khuyên từ chuyên gia.", "category": "huong-dan", "priority": "tier3", "area": [], "tags": ["hợp đồng", "thuê xe cẩu", "pháp lý"], "keywords": {"primary": "thuê xe cẩu có cần hợp đồng không", "secondary": ["hợp đồng thuê cẩu"], "lsi": ["pháp lý", "trách nhiệm"]}},
    {"id": 79, "slug": "bao-hiem-xe-cau-quy-dinh", "title": "Bảo Hiểm Xe Cẩu — Quy Định & Trách Nhiệm Khi Sự Cố", "description": "Quy định bảo hiểm xe cẩu tại Việt Nam. Ai chịu trách nhiệm khi sự cố? Bảo hiểm bắt buộc và tự nguyện.", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["bảo hiểm", "quy định", "sự cố"], "keywords": {"primary": "bảo hiểm xe cẩu quy định", "secondary": ["trách nhiệm sự cố xe cẩu"], "lsi": ["tai nạn", "bồi thường"]}},
    {"id": 80, "slug": "xe-cau-lam-viec-duoi-duong-day-dien", "title": "Xe Cẩu Làm Việc Dưới Đường Dây Điện — An Toàn Điện", "description": "Quy định an toàn khi xe cẩu làm việc gần đường dây điện cao thế. Khoảng cách tối thiểu, giấy phép, biện pháp bảo vệ.", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["an toàn điện", "đường dây điện", "quy định"], "keywords": {"primary": "xe cẩu làm việc dưới đường dây điện", "secondary": ["an toàn điện xe cẩu"], "lsi": ["cao thế", "khoảng cách"]}},
    {"id": 81, "slug": "kiem-dinh-xe-cau-dinh-ky", "title": "Kiểm Định Xe Cẩu Định Kỳ — Quy Trình & Lịch Kiểm Tra", "description": "Hướng dẫn kiểm định xe cẩu định kỳ. Lịch kiểm tra theo quy định. Hồ sơ cần chuẩn bị. Nơi kiểm định uy tín.", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["kiểm định", "định kỳ", "quy trình"], "keywords": {"primary": "kiểm định xe cẩu định kỳ", "secondary": ["quy trình kiểm định cẩu"], "lsi": ["an toàn", "chứng nhận"]}},
    {"id": 82, "slug": "cau-hang-khi-troi-mua-gio", "title": "Cẩu Hàng Khi Trời Mưa Gió — Có An Toàn Không?", "description": "Có nên cẩu hàng khi trời mưa gió? Giới hạn gió cho xe cẩu. Khi nào phải dừng cẩu? Biện pháp an toàn.", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["mưa gió", "an toàn", "thời tiết"], "keywords": {"primary": "cẩu hàng khi trời mưa gió", "secondary": ["xe cẩu mưa có an toàn"], "lsi": ["tốc độ gió", "giới hạn"]}},
    {"id": 83, "slug": "cach-tinh-trong-luong-hang-can-cau", "title": "Cách Tính Trọng Lượng Hàng Cần Cẩu — Công Thức & Bảng Tra", "description": "Hướng dẫn tính trọng lượng hàng cần cẩu. Công thức tính nhanh cho thép, bê tông, gỗ, máy móc. Bảng tra cứu.", "category": "huong-dan", "priority": "tier3", "area": [], "tags": ["trọng lượng", "tính toán", "công thức"], "keywords": {"primary": "cách tính trọng lượng hàng cần cẩu", "secondary": ["tính tải trọng cẩu"], "lsi": ["khối lượng riêng", "bảng tra"]}},
    {"id": 84, "slug": "xu-huong-nganh-xe-cau-viet-nam-2026", "title": "Xu Hướng Ngành Xe Cẩu Việt Nam 2026 — Cơ Hội & Thách Thức", "description": "Phân tích xu hướng ngành cho thuê xe cẩu Việt Nam 2026. Tăng trưởng công nghiệp, nhu cầu cẩu nặng, công nghệ mới.", "category": "kien-thuc", "priority": "tier3", "area": [], "tags": ["xu hướng", "2026", "ngành xe cẩu"], "keywords": {"primary": "xu hướng ngành xe cẩu Việt Nam 2026", "secondary": ["thị trường xe cẩu"], "lsi": ["FDI", "công nghiệp hóa"]}},
    {"id": 85, "slug": "kinh-nghiem-lam-viec-voi-doi-cau", "title": "Kinh Nghiệm Làm Việc Với Đội Cẩu — 5 Điều Nên Biết", "description": "5 điều cần biết khi làm việc với đội cẩu. Chuẩn bị mặt bằng, tín hiệu, giám sát an toàn. Kinh nghiệm thực tế.", "category": "huong-dan", "priority": "tier3", "area": [], "tags": ["kinh nghiệm", "đội cẩu", "mẹo"], "keywords": {"primary": "kinh nghiệm làm việc với đội cẩu", "secondary": ["chuẩn bị thuê cẩu"], "lsi": ["mặt bằng", "tín hiệu"]}},

    # ═══════════════════════════════════════════════════════════════
    # TIER 4: AI/AEO OPTIMIZE — Câu hỏi phổ biến (15 bài)
    # ═══════════════════════════════════════════════════════════════

    {"id": 86, "slug": "cau-8-tan-cau-duoc-bao-nhieu-kg", "title": "Cẩu 8 Tấn Cẩu Được Bao Nhiêu Kg? — Bảng Tải Trọng", "description": "Xe cẩu 8 tấn cẩu được tối đa 8.000 kg (8 tấn) ở tầm gần. Tải trọng giảm khi tầm với xa hơn. Xem bảng chi tiết.", "category": "kien-thuc", "priority": "tier4", "area": [], "tags": ["8 tấn", "tải trọng", "Q&A"], "keywords": {"primary": "cẩu 8 tấn cẩu được bao nhiêu kg", "secondary": ["xe cẩu 8 tấn nâng bao nhiêu"], "lsi": ["tải trọng nâng", "tầm với"]}},
    {"id": 87, "slug": "xe-cau-co-may-loai", "title": "Xe Cẩu Có Mấy Loại? — Phân Loại Đầy Đủ A-Z", "description": "Xe cẩu có 6 loại chính: cẩu tự hành, cẩu bánh xích, cẩu tháp, cẩu cổng, cẩu nổi, cẩu gắn trên xe tải. Chi tiết từng loại.", "category": "kien-thuc", "priority": "tier4", "area": [], "tags": ["phân loại", "các loại cẩu"], "keywords": {"primary": "xe cẩu có mấy loại", "secondary": ["phân loại xe cẩu"], "lsi": ["truck crane", "crawler crane"]}},
    {"id": 88, "slug": "khi-nao-can-thue-xe-cau-huong-dan", "title": "Khi Nào Cần Thuê Xe Cẩu? — Hướng Dẫn Cho Người Mới", "description": "Bạn cần thuê xe cẩu khi: vật nặng trên 500kg, lên cao trên 3m, khu vực hẹp không thể dùng cần cẩu tay. Xem chi tiết.", "category": "huong-dan", "priority": "tier4", "area": [], "tags": ["hướng dẫn", "người mới"], "keywords": {"primary": "khi nào cần thuê xe cẩu hướng dẫn", "secondary": ["ai cần thuê cẩu"], "lsi": ["vật nặng", "lên cao"]}},
    {"id": 89, "slug": "xe-cau-10-tan-cau-duoc-gi", "title": "Xe Cẩu 10 Tấn Cẩu Được Gì? — Danh Sách Vật Cẩu Phổ Biến", "description": "Xe cẩu 10 tấn cẩu được: container 20ft, máy phát điện, bồn nước lớn, dầm thép, máy xây dựng. Xem bảng chi tiết.", "category": "kien-thuc", "priority": "tier4", "area": [], "tags": ["10 tấn", "cẩu được gì"], "keywords": {"primary": "xe cẩu 10 tấn cẩu được gì", "secondary": ["cẩu 10 tấn dùng cho việc gì"], "lsi": ["container", "máy phát điện"]}},
    {"id": 90, "slug": "thue-xe-cau-can-chuan-bi-gi", "title": "Thuê Xe Cẩu Cần Chuẩn Bị Gì? — Checklist Đầy Đủ", "description": "Checklist chuẩn bị trước khi thuê xe cẩu: mặt bằng, trọng lượng hàng, chiều cao nâng, đường vào, điện lưới, giấy phép.", "category": "huong-dan", "priority": "tier4", "area": [], "tags": ["checklist", "chuẩn bị"], "keywords": {"primary": "thuê xe cẩu cần chuẩn bị gì", "secondary": ["chuẩn bị thuê cẩu"], "lsi": ["mặt bằng", "giấy phép"]}},
    {"id": 91, "slug": "xe-cau-nho-nhat-la-may-tan", "title": "Xe Cẩu Nhỏ Nhất Là Mấy Tấn? — Cẩu Mini Cho Hẻm Nhỏ", "description": "Xe cẩu nhỏ nhất phổ biến là 2.5–3.5 tấn. Kích thước nhỏ gọn, vào được hẻm 3m. Phù hợp cẩu bồn nước, cây cảnh.", "category": "kien-thuc", "priority": "tier4", "area": [], "tags": ["cẩu mini", "nhỏ nhất", "hẻm"], "keywords": {"primary": "xe cẩu nhỏ nhất là mấy tấn", "secondary": ["cẩu mini bao nhiêu tấn"], "lsi": ["hẻm nhỏ", "3.5 tấn"]}},
    {"id": 92, "slug": "xe-cau-25-tan-tam-voi-bao-nhieu-met", "title": "Xe Cẩu 25 Tấn Tầm Với Bao Nhiêu Mét? — Thông Số Kỹ Thuật", "description": "Xe cẩu 25 tấn có tầm với tối đa 28-33 mét tùy model. Tải trọng giảm khi tầm với xa. Bảng tải chi tiết.", "category": "kien-thuc", "priority": "tier4", "area": [], "tags": ["25 tấn", "tầm với", "thông số"], "keywords": {"primary": "xe cẩu 25 tấn tầm với bao nhiêu mét", "secondary": ["thông số xe cẩu 25 tấn"], "lsi": ["boom", "bảng tải"]}},
    {"id": 93, "slug": "cau-bon-nuoc-mat-bao-lau", "title": "Cẩu Bồn Nước Mất Bao Lâu? — Thời Gian Thực Tế", "description": "Cẩu bồn nước mất khoảng 30-60 phút tùy tầng cao và vị trí. Bao gồm: chuẩn bị 15 phút, cẩu 10-15 phút, cố định 15 phút.", "category": "huong-dan", "priority": "tier4", "area": [], "tags": ["thời gian", "bồn nước"], "keywords": {"primary": "cẩu bồn nước mất bao lâu", "secondary": ["thời gian cẩu bồn nước"], "lsi": ["30 phút", "tầng cao"]}},
    {"id": 94, "slug": "xe-cau-di-duoc-bao-nhieu-km-h", "title": "Xe Cẩu Đi Được Bao Nhiêu Km/h? — Tốc Độ Di Chuyển", "description": "Xe cẩu tự hành di chuyển 40-60 km/h trên đường. Khi có tải, tốc độ giảm còn 20-40 km/h. Quy định tốc độ.", "category": "kien-thuc", "priority": "tier4", "area": [], "tags": ["tốc độ", "di chuyển"], "keywords": {"primary": "xe cẩu đi được bao nhiêu km/h", "secondary": ["tốc độ xe cẩu"], "lsi": ["di chuyển", "đường bộ"]}},
    {"id": 95, "slug": "1-ca-cau-la-bao-nhieu-gio", "title": "1 Ca Cẩu Là Bao Nhiêu Giờ? — Cách Tính Thời Gian Thuê", "description": "1 ca cẩu tiêu chuẩn là 8 giờ làm việc (không tính di chuyển). Ngoài giờ tính phí thêm. Cách tính chi phí.", "category": "huong-dan", "priority": "tier4", "area": [], "tags": ["ca cẩu", "thời gian", "tính giá"], "keywords": {"primary": "1 ca cẩu là bao nhiêu giờ", "secondary": ["ca cẩu bao nhiêu giờ"], "lsi": ["8 giờ", "ngoài giờ"]}},
    {"id": 96, "slug": "cau-nang-100-tan-co-duoc-khong", "title": "Cẩu Nặng 100 Tấn Có Được Không? — Giới Hạn Xe Cẩu", "description": "Cẩu 100 tấn cần xe cẩu trên 120 tấn để đảm bảo an toàn (hệ số 1.2-1.5). Ở Việt Nam có cẩu đến 500 tấn.", "category": "kien-thuc", "priority": "tier4", "area": [], "tags": ["100 tấn", "giới hạn", "cẩu nặng"], "keywords": {"primary": "cẩu nặng 100 tấn có được không", "secondary": ["xe cẩu lớn nhất"], "lsi": ["hệ số an toàn", "500 tấn"]}},
    {"id": 97, "slug": "xe-cau-can-may-nguoi-van-hanh", "title": "Xe Cẩu Cần Mấy Người Vận Hành? — Đội Cẩu Gồm Ai?", "description": "Đội cẩu tiêu chuẩn gồm 3-5 người: 1 lái cẩu, 1-2 tín hiệu viên, 1-2 thợ buộc. Vai trò từng người.", "category": "kien-thuc", "priority": "tier4", "area": [], "tags": ["đội cẩu", "nhân sự", "vận hành"], "keywords": {"primary": "xe cẩu cần mấy người vận hành", "secondary": ["đội cẩu gồm mấy người"], "lsi": ["lái cẩu", "tín hiệu viên"]}},
    {"id": 98, "slug": "xe-cau-co-vao-hem-duoc-khong", "title": "Xe Cẩu Có Vào Hẻm Được Không? — Xe Cẩu Mini Cho Ngõ Nhỏ", "description": "Xe cẩu 3.5 tấn vào được hẻm rộng 3m. Xe cẩu 5 tấn cần hẻm 3.5m. Giải pháp cho hẻm cực nhỏ.", "category": "huong-dan", "priority": "tier4", "area": [], "tags": ["hẻm nhỏ", "cẩu mini", "giải pháp"], "keywords": {"primary": "xe cẩu có vào hẻm được không", "secondary": ["cẩu cho hẻm nhỏ"], "lsi": ["3 mét", "ngõ ngách"]}},
    {"id": 99, "slug": "cau-bon-nuoc-tang-4-can-cau-may-tan", "title": "Cẩu Bồn Nước Tầng 4 Cần Cẩu Mấy Tấn? — Lời Khuyên", "description": "Cẩu bồn nước 1000L lên tầng 4 (12-14m) cần xe cẩu tối thiểu 5 tấn. Nếu vị trí xa, cần 8 tấn. Chi tiết.", "category": "huong-dan", "priority": "tier4", "area": [], "tags": ["bồn nước tầng 4", "mấy tấn"], "keywords": {"primary": "cẩu bồn nước tầng 4 cần cẩu mấy tấn", "secondary": ["cẩu bồn lên tầng 4"], "lsi": ["5 tấn", "tầm với"]}},
    {"id": 100, "slug": "thue-xe-cau-o-dau-uy-tin", "title": "Thuê Xe Cẩu Ở Đâu Uy Tín? — 5 Tiêu Chí Chọn Đội Cẩu", "description": "5 tiêu chí chọn đội cẩu uy tín: kinh nghiệm, giấy phép, bảo hiểm, giá minh bạch, đánh giá khách hàng. Hướng dẫn chi tiết.", "category": "huong-dan", "priority": "tier4", "area": [], "tags": ["uy tín", "chọn đội cẩu", "tiêu chí"], "keywords": {"primary": "thuê xe cẩu ở đâu uy tín", "secondary": ["chọn đội cẩu nào tốt"], "lsi": ["giấy phép", "đánh giá"]}},
]


def get_keywords():
    """Return the full keyword matrix."""
    return KEYWORDS


def get_keywords_by_tier(tier: str):
    """Filter keywords by priority tier."""
    return [k for k in KEYWORDS if k["priority"] == tier]


def get_keywords_by_area(area: str):
    """Filter keywords by target area."""
    return [k for k in KEYWORDS if area in k["area"]]


def get_keywords_by_category(category: str):
    """Filter keywords by content category."""
    return [k for k in KEYWORDS if k["category"] == category]


def export_json(output_path: str = None):
    """Export keyword matrix as JSON."""
    if output_path is None:
        output_path = os.path.join(os.path.dirname(__file__), "keywords.json")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(KEYWORDS, f, ensure_ascii=False, indent=2)
    print(f"✅ Exported {len(KEYWORDS)} keywords to {output_path}")
    return output_path


def print_stats():
    """Print keyword matrix statistics."""
    total = len(KEYWORDS)
    tiers = {}
    categories = {}
    areas = {}

    for k in KEYWORDS:
        tier = k["priority"]
        tiers[tier] = tiers.get(tier, 0) + 1
        cat = k["category"]
        categories[cat] = categories.get(cat, 0) + 1
        for a in k["area"]:
            areas[a] = areas.get(a, 0) + 1

    print(f"\n📊 KEYWORD MATRIX STATISTICS")
    print(f"{'='*40}")
    print(f"Total keywords: {total}")
    print(f"\n🎯 By Tier:")
    for t, c in sorted(tiers.items()):
        print(f"  {t}: {c} keywords")
    print(f"\n📂 By Category:")
    for cat, c in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"  {cat}: {c} keywords")
    print(f"\n📍 By Area:")
    for a, c in sorted(areas.items(), key=lambda x: -x[1]):
        print(f"  {a}: {c} keywords")


if __name__ == "__main__":
    print_stats()
    export_json()
